# Generated by Django 4.1.3 on 2022-12-16 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_merge_0002_alter_post_text_0003_alter_post_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='AgregarComentario',
        ),
    ]
